version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: mashup_postgres
    environment:
      POSTGRES_DB: mashup_agent
      POSTGRES_USER: mashup_user
      POSTGRES_PASSWORD: HEDARpass=256671
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: mashup_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data:
